application: myapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /images
  static_dir: static/images

- url: /index.html
  script: src/home.php
  
- url: /database.php
  script: src/database.php
  
- url: /
  script: src/home.php



  
  
  
 